import { AgGridReact } from 'ag-grid-react';
import React, { useMemo, useRef, useState } from 'react';
import AGTable, { ColDefType } from 'src/common/components/AGTable';
import { useAppDispatch } from 'src/redux/hooks';
import { setSelectedSymbol } from 'src/redux/slices/option';

type WatchlistData = {
    symbolISIN: string;
    symbolTitle: string;
    lastTradedPrice: number;
    closingPrice: number;
    totalNumberOfSharesTraded: number;
    totalTradeValue: number;
};

const Watchlist = () => {
    //
    const appDispatch = useAppDispatch();

    const gridRef = useRef<AgGridReact<WatchlistData>>(null);

    gridRef.current?.api.forEachNode(({ data }) => {
        data?.closingPrice;
    });

    const [rowData] = useState([
        {
            symbolISIN: 'IRO1MKBT0001',
            note: null,
            stopLoss: 0,
            takeProfit: 0,
            commentCount: 0,
            insCode: '22811176775480091',
            companyISIN: 'IRO1MKBT0008',
            symbolTitle: 'اخابر',
            companyName: 'مخابرات ایران',
            enCompanyName: 'Iran Tele. Co.',
            highestTradePriceOfTradingDay: 7420,
            lowestTradePriceOfTradingDay: 7090,
            closingPrice: 7270,
            openPrice: 7390,
            highThreshold: 7910,
            lowThreshold: 6890,
            totalNumberOfSharesTraded: 33343344,
            totalNumberOfTrades: 2500,
            totalTradeValue: 2423100672,
            lastTradedPrice: 7170,
            lastTradedDate: '2022-09-06T09:00:53',
            firstTradedPrice: 7390,
            preClosingPrice: 0,
            lastTradedPriceVar: 0,
            lastTradedPriceVarPercent: -3.11,
            closingPriceVar: 0,
            closingPriceVarPercent: -1.76,
            symbolGroupCode: 'N1',
            bestBuyLimitQuantity_1: 1000,
            bestSellLimitQuantity_1: 1000,
            numberOfOrdersAtBestBuy_1: 0,
            numberOfOrdersAtBestSell_1: 0,
            bestBuyLimitPrice_1: 7150,
            bestSellLimitPrice_1: 7170,
            sectorCode: '64',
            unitCount: 60000000000,
            marketUnit: 'Exchange',
            orderPriceTickSize: 10,
            baseVolume: 17291066,
            symbolOrderState: 'OrderEntryAuthorized',
            symbolTradeState: 'Open',
            groupState: 'Forbidden',
            symbolState: 'OrderEntryAuthorized_Open',
            key: 1,
        },
        {
            symbolISIN: 'IRO1FOLD0001',
            note: null,
            stopLoss: 0,
            takeProfit: 0,
            commentCount: 0,
            insCode: '46348559193224090',
            companyISIN: 'IRO1FOLD0009',
            symbolTitle: 'فولاد',
            companyName: 'فولاد مبارکه اصفهان',
            enCompanyName: 'S*Mobarakeh Steel',
            highestTradePriceOfTradingDay: 5100,
            lowestTradePriceOfTradingDay: 5020,
            closingPrice: 5060,
            openPrice: 5080,
            highThreshold: 5430,
            lowThreshold: 4730,
            totalNumberOfSharesTraded: 34701518,
            totalNumberOfTrades: 3234,
            totalTradeValue: 1756085504,
            lastTradedPrice: 5070,
            lastTradedDate: '2022-09-06T09:00:51',
            firstTradedPrice: 5080,
            preClosingPrice: 0,
            lastTradedPriceVar: 0,
            lastTradedPriceVarPercent: -0.2,
            closingPriceVar: 0,
            closingPriceVarPercent: -0.39,
            symbolGroupCode: 'N1',
            bestBuyLimitQuantity_1: 42172,
            bestSellLimitQuantity_1: 1000,
            numberOfOrdersAtBestBuy_1: 0,
            numberOfOrdersAtBestSell_1: 0,
            bestBuyLimitPrice_1: 5060,
            bestSellLimitPrice_1: 5070,
            sectorCode: '27',
            unitCount: 530000000000,
            marketUnit: 'Exchange',
            orderPriceTickSize: 10,
            baseVolume: 23346304,
            symbolOrderState: 'OrderEntryAuthorized',
            symbolTradeState: 'Open',
            groupState: 'Forbidden',
            symbolState: 'OrderEntryAuthorized_Open',
            key: 2,
        },
        {
            symbolISIN: 'IRO1PNBA0001',
            note: null,
            stopLoss: 0,
            takeProfit: 0,
            commentCount: 0,
            insCode: '35366681030756042',
            companyISIN: 'IRO1PNBA0003',
            symbolTitle: 'شبندر',
            companyName: 'پالایش نفت بندرعباس',
            enCompanyName: 'B.A Oil Refinie',
            highestTradePriceOfTradingDay: 7400,
            lowestTradePriceOfTradingDay: 7180,
            closingPrice: 7250,
            openPrice: 7400,
            highThreshold: 7860,
            lowThreshold: 6840,
            totalNumberOfSharesTraded: 30373609,
            totalNumberOfTrades: 3356,
            totalTradeValue: 2203461632,
            lastTradedPrice: 7220,
            lastTradedDate: '2022-09-06T09:00:55',
            firstTradedPrice: 7400,
            preClosingPrice: 0,
            lastTradedPriceVar: 0,
            lastTradedPriceVarPercent: -1.77,
            closingPriceVar: 0,
            closingPriceVarPercent: -1.36,
            symbolGroupCode: 'N1',
            bestBuyLimitQuantity_1: 27834,
            bestSellLimitQuantity_1: 12832,
            numberOfOrdersAtBestBuy_1: 0,
            numberOfOrdersAtBestSell_1: 0,
            bestBuyLimitPrice_1: 7220,
            bestSellLimitPrice_1: 7230,
            sectorCode: '23',
            unitCount: 134341922000,
            marketUnit: 'Exchange',
            orderPriceTickSize: 10,
            baseVolume: 15831135,
            symbolOrderState: 'OrderEntryAuthorized',
            symbolTradeState: 'Open',
            groupState: 'Forbidden',
            symbolState: 'OrderEntryAuthorized_Open',
            key: 3,
        },
        {
            symbolISIN: 'IRO1PNBA0002',
            note: null,
            stopLoss: 0,
            takeProfit: 0,
            commentCount: 0,
            insCode: '51234238775438234',
            companyISIN: 'IRO1PNBA0003',
            symbolTitle: 'شبندر2',
            companyName: 'پالایش نفت بندرعباس',
            enCompanyName: 'B.A Oil Refinie',
            highestTradePriceOfTradingDay: 7860,
            lowestTradePriceOfTradingDay: 7860,
            closingPrice: 7860,
            openPrice: 7860,
            highThreshold: 7864,
            lowThreshold: 6836,
            totalNumberOfSharesTraded: 11090000,
            totalNumberOfTrades: 1,
            totalTradeValue: 871673984,
            lastTradedPrice: 7860,
            lastTradedDate: '2022-09-06T10:46:56',
            firstTradedPrice: 7860,
            preClosingPrice: 0,
            lastTradedPriceVar: 510,
            lastTradedPriceVarPercent: 6.94,
            closingPriceVar: 0,
            closingPriceVarPercent: 6.94,
            symbolGroupCode: '1O',
            bestBuyLimitQuantity_1: 0,
            bestSellLimitQuantity_1: 0,
            numberOfOrdersAtBestBuy_1: 0,
            numberOfOrdersAtBestSell_1: 0,
            bestBuyLimitPrice_1: 0,
            bestSellLimitPrice_1: 0,
            sectorCode: '23',
            unitCount: 134341922000,
            marketUnit: 'Exchange',
            orderPriceTickSize: 1,
            baseVolume: 1,
            symbolOrderState: 'OrderEntryAuthorized',
            symbolTradeState: 'Open',
            groupState: 'ContinuousTrading',
            symbolState: 'OrderEntryAuthorized_Open',
            key: 4,
        },
        {
            symbolISIN: 'IRO1PNBA0003',
            note: null,
            stopLoss: 0,
            takeProfit: 0,
            commentCount: 0,
            insCode: '39549984459336635',
            companyISIN: 'IRO1PNBA0003',
            symbolTitle: 'شبندر3',
            companyName: 'پالایش نفت بندرعباس',
            enCompanyName: 'B.A Oil Refinie',
            highestTradePriceOfTradingDay: 0,
            lowestTradePriceOfTradingDay: 0,
            closingPrice: 7350,
            openPrice: 0,
            highThreshold: 7717,
            lowThreshold: 6983,
            totalNumberOfSharesTraded: 0,
            totalNumberOfTrades: 0,
            totalTradeValue: 0,
            lastTradedPrice: 7340,
            lastTradedDate: '0001-01-01T00:00:00',
            firstTradedPrice: 0,
            preClosingPrice: 0,
            lastTradedPriceVar: 0,
            lastTradedPriceVarPercent: 0,
            closingPriceVar: 0,
            closingPriceVarPercent: 0,
            symbolGroupCode: 'Y1',
            bestBuyLimitQuantity_1: 0,
            bestSellLimitQuantity_1: 0,
            numberOfOrdersAtBestBuy_1: 0,
            numberOfOrdersAtBestSell_1: 0,
            bestBuyLimitPrice_1: 0,
            bestSellLimitPrice_1: 0,
            sectorCode: '23',
            unitCount: 134341922000,
            marketUnit: 'Exchange',
            orderPriceTickSize: 1,
            baseVolume: 1,
            symbolOrderState: 'OrderEntryForbidden',
            symbolTradeState: 'Suspended',
            groupState: 'Forbidden',
            symbolState: 'OrderEntryForbidden_Suspended',
            key: 5,
        },
        {
            symbolISIN: 'IRO1PNBA0004',
            note: null,
            stopLoss: 0,
            takeProfit: 0,
            commentCount: 0,
            insCode: '8444268204724843',
            companyISIN: 'IRO1PNBA0003',
            symbolTitle: 'شبندر4',
            companyName: 'پالایش نفت بندرعباس',
            enCompanyName: 'B.A Oil Refinie',
            highestTradePriceOfTradingDay: 0,
            lowestTradePriceOfTradingDay: 0,
            closingPrice: 7350,
            openPrice: 0,
            highThreshold: 7864,
            lowThreshold: 6836,
            totalNumberOfSharesTraded: 0,
            totalNumberOfTrades: 0,
            totalTradeValue: 0,
            lastTradedPrice: 7340,
            lastTradedDate: '0001-01-01T00:00:00',
            firstTradedPrice: 0,
            preClosingPrice: 0,
            lastTradedPriceVar: 0,
            lastTradedPriceVarPercent: 0,
            closingPriceVar: 0,
            closingPriceVarPercent: 0,
            symbolGroupCode: '1B',
            bestBuyLimitQuantity_1: 0,
            bestSellLimitQuantity_1: 0,
            numberOfOrdersAtBestBuy_1: 0,
            numberOfOrdersAtBestSell_1: 0,
            bestBuyLimitPrice_1: 0,
            bestSellLimitPrice_1: 0,
            sectorCode: '23',
            unitCount: 134341922000,
            marketUnit: 'Exchange',
            orderPriceTickSize: 1,
            baseVolume: 1,
            symbolOrderState: 'OrderEntryForbidden',
            symbolTradeState: 'Open',
            groupState: 'ContinuousTrading',
            symbolState: 'OrderEntryForbidden_Open',
            key: 6,
        },
    ]);

    const Columns = useMemo(
        (): ColDefType<WatchlistData>[] => [
            { headerName: 'نماد', field: 'symbolTitle' },
            { headerName: 'قیمت لحظه ای', field: 'lastTradedPrice', type: 'sepratedNumber' },
            { headerName: 'قیمت پایانی', field: 'closingPrice', type: 'sepratedNumber' },
            { headerName: 'حجم معاملات', field: 'totalNumberOfSharesTraded', type: 'abbreviatedNumber' },
            { headerName: 'ارزش معاملات', field: 'totalTradeValue', type: 'abbreviatedNumber' },
            { headerName: 'عملیات', field: 'symbolISIN' },
        ],
        [],
    );

    return (
        <div className="px-3 py-1 flex flex-col h-full">
            <div className="py-3">actions</div>
            <div className="grow">
                <AGTable
                    rowData={rowData}
                    columnDefs={Columns}
                    onRowClicked={({ data }) => data?.symbolISIN && appDispatch(setSelectedSymbol(data?.symbolISIN))}
                />
            </div>
        </div>
    );
};

export default Watchlist;
